# Levels for disease status
# S = Susceptible
# PS = Infected, presymptomatic
# IS = Infected, symptomatic
# IA = Infected, asymptomatic 
# R = Recovered

# ============================================================================ # 
# Incubation period
# ---------------------------------------------------------------------------- #
# Input:
# n = Number of values to be generated by the distribution
# shape = shape of gamma distribution
# scale = scale of gamma distribution
# Output:
# n values drawn from incubation period distribution
inc.period <- function(n=1, shape=1.58, scale=7.11){
  return(rweibull(n, shape=1.58, scale=7.11))
  # return(rgamma(n, shape=5.807, scale=0.948))
}

prop.symp <- function(n=1, teacher=T, vaccination_flag=F){
  if(vaccination_flag) prop_symp <- runif(n, min=0.3, max=0.7)
  else{
    if(teacher) prop_symp <- runif(n, min=0.75, max=0.83)
    else prop_symp <- runif(n, min=0.4, max=0.85)
  }
  return(prop_symp)
}

# min=0.3, max=0.7
asymp.scale <- function(n=1, min=0.3, max=0.7){
  return(runif(n, min=min, max=max))
}

susc.scale <- function(n=1, mean=0.64, sd=0.09){
  return(rtruncnorm(n, a=0, mean=mean, sd=sd))
}

infec.scale <- function(n=1, mean=0.85, sd=0.1){
  return(rtruncnorm(n, a=0, mean=mean, sd=sd))
}

contact.infec.scale <- function(n=1, min=0.5, max=0.85){
  return(runif(n, min=min, max=max))
}

infectiousness <- function(t, scaling=1.0, R0=1.05){
  gen_time <- dweibull(t, shape=1.6, scale=6.84)
  infectivity <- ifelse(gen_time*R0*scaling>=0, gen_time*R0*scaling, 0)
  return(infectivity)
}

susc.vacc.scale <- function(n=1, min=1-0.94, max=1-0.55){
  return(runif(n, min=min, max=max))
}

prob.trans <- function(time, infec=T, susc=F, asymp=F, vacc=F){
  infectivity <- infectiousness(time)
  prob_trans <- infectivity*ifelse(infec, infec.scale(), 1)*ifelse(asymp, asymp.scale(), 1)
  return(prob_trans)
}
